---
title: "Resume"
editor: 
  markdown: 
    wrap: 72
---

# Education

<p style="display: flex; justify-content: space-between;">

University of British Columbia, Vancouver, BC<br> Master of Geomatics
for Environmental Management Sept. 2025 - May 2026

</p>

<p style="display: flex; justify-content: space-between;">

University of British Columbia, Vancouver, BC<br> Bachelor of Wood
Products Processing, Minor in Commerce Sept. 2022 - May 2025

</p>

<p style="display: flex; justify-content: space-between;">

Beijing Forestry University, Beijing, China<br> Bachelor of Wood Science
and Engineering Sept. 2019 - June 2022

</p>

# Publications

*Peer-reviewed publication:*

-   Jin, C., Zhu, S., & Feng, H. (2025). *Life Cycle Assessment of Engineered Wood Products in the Building Sector: A Review.* Buildings, 15(22), 4193. [https://doi.org/10.3390/buildings15224193](https://doi.org/10.3390/buildings15224193)

# Volunteer/Work Experience

### Volunteer Research Assistant  
**University of British Columbia, Vancouver, BC, Canada**  
*Jan 2024 – Sept 2024*  
- Collected, sorted, and recorded large datasets with accuracy and efficiency.  
- Maintained organized records to support data analysis and reporting.  
- Collaborated closely with team members to ensure project goals were met on time.  

### Laboratory Quality Inspector  
**Tucson Wood, Shengzhou, Zhejiang, China**  
*June 2022 – July 2022*  
- Evaluated the quality of panels and boards, including scratch resistance, hot/cold resistance, and formaldehyde content, ensuring product reliability and customer satisfaction.  
- Recorded experimental data, summarized results, and provided feedback to the R&D workshops.  
- Assisted with laboratory visits, collaborating with team members and hosting over 50 clients.  
